name: hw3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3
  - backcall=0.2.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - dbus=1.13.6
  - decorator=5.1.1
  - expat=2.4.1
  - ffmpeg=4.3.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - harfbuzz=2.8.2
  - hdf5=1.10.6
  - icu=68.1
  - ipython=7.31.1
  - jasper=1.900.1
  - jbig=2.1
  - jedi=0.18.1
  - jpeg=9d
  - krb5=1.19.2
  - lame=3.100
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.78.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.68.3
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libogg=1.3.4
  - libopenblas=0.3.17
  - libopencv=4.5.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.16.0
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.2
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.3
  - nettle=3.6
  - nspr=4.30
  - nss=3.67
  - numpy=1.21.1
  - opencv=4.5.2
  - openh264=2.1.1
  - openssl=1.1.1m
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - pixman=0.40.0
  - prompt-toolkit=3.0.20
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py-opencv=4.5.2
  - pygments=2.11.2
  - python=3.9.7
  - python_abi=3.9
  - qt=5.12.9
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.37.2
  - tk=8.6.11
  - traitlets=5.1.1
  - tzdata=2021e
  - wcwidth=0.2.5
  - wheel=0.37.1
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - cycler==0.11.0
    - fonttools==4.29.1
    - ipdb==0.13.9
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - packaging==21.3
    - pillow==9.0.1
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - scipy==1.8.0
    - six==1.16.0
    - toml==0.10.2
    - tqdm==4.62.3
