name: vp2022
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - numpy=1.21.1
  - opencv=4.5.2
  - python=3.9.7
  - pip:
    - cycler==0.11.0
    - fonttools==4.29.1
    - ipdb==0.13.9
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - packaging==21.3
    - pillow==9.0.1
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - scipy==1.8.0
    - six==1.16.0
    - toml==0.10.2
