'''VIDEO STABILIZATION CONST.'''
MAX_CORNERS = 500
QUALITY_LEVEL = 0.01
MIN_DISTANCE = 30
BLOCK_SIZE = 3
SMOOTH_RADIUS = 5

'''BACKGROUND SUBTRACTION CONST.'''
BW_MEDIUM = 1
BW_NARROW = 0.1
LEGS_HEIGHT = 805
SHOES_HEIGHT = 870
SHOULDERS_HEIGHT = 405
BLUE_MASK_THR = 140
WINDOW_WIDTH = 500
WINDOW_HEIGHT = 1000
FACE_WINDOW_HEIGHT = 250
FACE_WINDOW_WIDTH = 300

'''MATTING CONST.'''
EPSILON_NARROW_BAND = 0.99
ERODE_ITERATIONS = 6
DILATE_ITERATIONS = 5
GEODISTK_ITERATIONS = 1
REFINEMENT_WINDOW_SIZE = 20
KDE_BW = 1
R = 2
