name: vpproj22
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - numpy=1.21.1
  - opencv=4.5.4
  - pip:
    - matplotlib==3.4.3
    - opencv==4.5.4
    - pillow==9.0.1
    - pixman==0.40.0
    - python-dateutil==2.8.2
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - numpy==1.22.3
    - geodistk==0.1.7
    - numpy==1.22.3
    - six==1.16.0
